project:
  type: book
  pre-render: R/generate-zip.R

book:
  title: "Leer Microsoft Access"
  author: "Ben Welman"
  date: today
  date-format: long
  google-analytics: "G-YME027QNPL"
  site-url: https://leeraccess.netlify.app/
  repo-url: https://github.com/bwelman/leeraccess
  repo-actions: [issue]
  description: "Een taakgericht studieboek."

  chapters:
    - index.qmd
    - preface.qmd
    - part: "Basis"
      chapters:
        - 01-intro.qmd
        - 02-explore.qmd
        - 03-data.qmd
        - 04-tables.qmd
        - 05-queries.qmd
        - 06-forms.qmd
        - 07-reports.qmd
    - part: "Gevorderd"
      chapters:
        - 08-integration.qmd
        - 09-tools.qmd
        - 10-macros.qmd
        - 11-normalization.qmd
execute:
  freeze: auto

lang: nl

language:
  en:
    crossref-prp-title: "Task"
  nl:
    crossref-prp-title: "Taak"

format:
  html:
    include-after-body: include/webex-nl.js
    css: include/webex.css
    theme:
      - cosmo
      - include/textbook.scss
    cover-image: images/cover-access.svg
    fig-width: 6
    fig-asp: 0.618
    fig-align: center
    code-fold: false
    link-external-newwindow: true
    callout-appearance: simple
    author-meta: "Ben Welman"
    description-meta: "Met dit taak georienteerd studieboek leer je werken met Microsoft Access."
    keywords: ["Access", "databases", "tabellen", "queries", "formulieren", "rapporten", "macros"]

knitr:
  opts_chunk:
    echo: false
    warning: false
    message: false
    cache: false
